### ISSUE TITLE
question about who to installation open chain on redhat openshift free plan ( 512 mb ram limited )

### ISSUE THREAD

**Issue by syntox** [openchain/wallet#1]
hi openchain support team
i'm very interesting to know who to make my own version of openchain install on openshift redhat free plan ( 512 mb ram limited )
https://developers.openshift.com/en/managing-common-rhc-commands.html
please tell me to finish it easily :+1: 
thanks for taking your time ,goodbye

**Comment by Flavien** [comment]
Follow [these steps](https://docs.docker.com/engine/installation/rhel/) to install Docker on Red Hat Enterprise Linux, then follow instructions on [this page](https://docs.openchain.org/en/latest/general/docker-deployment.html) to deploy Openchain.
