### ISSUE TITLE
JS error while signin in using a passphrase

### ISSUE THREAD

**Issue by raymens** [openchain/wallet#2]
After generating a passphrase on the testnet wallet I tried to login using it but received the following error:

![image](https://cloud.githubusercontent.com/assets/1369454/15144795/fa5bc3ea-16b1-11e6-8992-867136f5c2ab.png)

Using Edge on W10. Generating another passphrase didn't help.

**Comment by Flavien** [comment]
Make sure the word "Back" didn't get copied at the end of the passphrase.

**Comment by raymens** [comment]
Double checked and no. I just checked and the passphrases do work with Opera (webkit/blink). Might be a ChakraJS/Edge problem

**Comment by Flavien** [comment]
Seems to be related to this: https://github.com/bitpay/bitcore-lib/issues/53

**Comment by raymens** [comment]
Seems so yeah. An update from bitcore 0.13.11 to 0.13.15 should solve it.

**Comment by Flavien** [comment]
It should be resolved now (https://github.com/openchain/wallet/commit/09bdd7055a47c26dd7bf6c7391c1695439d769d3).
